/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as EmployeesReferencesRouteImport } from './routes/employees/references'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees/$employeeId'
import { Route as AuthAccessKeyRouteImport } from './routes/auth/access-key'
import { Route as AssetsReferencesRouteImport } from './routes/assets/references'
import { Route as AssetsAssetIdRouteImport } from './routes/assets/$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesReferencesRoute = EmployeesReferencesRouteImport.update({
  id: '/employees/references',
  path: '/employees/references',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccessKeyRoute = AuthAccessKeyRouteImport.update({
  id: '/auth/access-key',
  path: '/auth/access-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsReferencesRoute = AssetsReferencesRouteImport.update({
  id: '/assets/references',
  path: '/assets/references',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/references': typeof AssetsReferencesRoute
  '/auth/access-key': typeof AuthAccessKeyRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/references': typeof EmployeesReferencesRoute
  '/assets/': typeof AssetsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/references': typeof AssetsReferencesRoute
  '/auth/access-key': typeof AuthAccessKeyRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/references': typeof EmployeesReferencesRoute
  '/assets': typeof AssetsIndexRoute
  '/employees': typeof EmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/references': typeof AssetsReferencesRoute
  '/auth/access-key': typeof AuthAccessKeyRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/references': typeof EmployeesReferencesRoute
  '/assets/': typeof AssetsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets/$assetId'
    | '/assets/references'
    | '/auth/access-key'
    | '/employees/$employeeId'
    | '/employees/references'
    | '/assets/'
    | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets/$assetId'
    | '/assets/references'
    | '/auth/access-key'
    | '/employees/$employeeId'
    | '/employees/references'
    | '/assets'
    | '/employees'
  id:
    | '__root__'
    | '/'
    | '/assets/$assetId'
    | '/assets/references'
    | '/auth/access-key'
    | '/employees/$employeeId'
    | '/employees/references'
    | '/assets/'
    | '/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  AssetsReferencesRoute: typeof AssetsReferencesRoute
  AuthAccessKeyRoute: typeof AuthAccessKeyRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  EmployeesReferencesRoute: typeof EmployeesReferencesRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/references': {
      id: '/employees/references'
      path: '/employees/references'
      fullPath: '/employees/references'
      preLoaderRoute: typeof EmployeesReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/access-key': {
      id: '/auth/access-key'
      path: '/auth/access-key'
      fullPath: '/auth/access-key'
      preLoaderRoute: typeof AuthAccessKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/references': {
      id: '/assets/references'
      path: '/assets/references'
      fullPath: '/assets/references'
      preLoaderRoute: typeof AssetsReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  AssetsReferencesRoute: AssetsReferencesRoute,
  AuthAccessKeyRoute: AuthAccessKeyRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  EmployeesReferencesRoute: EmployeesReferencesRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
