/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as EmployeesIndexRouteImport } from './routes/employees/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as FinanceReferencesRouteImport } from './routes/finance/references'
import { Route as FinanceReconciliationsRouteImport } from './routes/finance/reconciliations'
import { Route as FinanceJournalEntriesRouteImport } from './routes/finance/journal-entries'
import { Route as EmployeesReferencesRouteImport } from './routes/employees/references'
import { Route as EmployeesEmployeeIdRouteImport } from './routes/employees/$employeeId'
import { Route as AuthAccessKeyRouteImport } from './routes/auth/access-key'
import { Route as AssetsReferencesRouteImport } from './routes/assets/references'
import { Route as AssetsAssetIdRouteImport } from './routes/assets/$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesIndexRoute = EmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReferencesRoute = FinanceReferencesRouteImport.update({
  id: '/finance/references',
  path: '/finance/references',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceReconciliationsRoute = FinanceReconciliationsRouteImport.update({
  id: '/finance/reconciliations',
  path: '/finance/reconciliations',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceJournalEntriesRoute = FinanceJournalEntriesRouteImport.update({
  id: '/finance/journal-entries',
  path: '/finance/journal-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesReferencesRoute = EmployeesReferencesRouteImport.update({
  id: '/employees/references',
  path: '/employees/references',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesEmployeeIdRoute = EmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccessKeyRoute = AuthAccessKeyRouteImport.update({
  id: '/auth/access-key',
  path: '/auth/access-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsReferencesRoute = AssetsReferencesRouteImport.update({
  id: '/assets/references',
  path: '/assets/references',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/references': typeof AssetsReferencesRoute
  '/auth/access-key': typeof AuthAccessKeyRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/references': typeof EmployeesReferencesRoute
  '/finance/journal-entries': typeof FinanceJournalEntriesRoute
  '/finance/reconciliations': typeof FinanceReconciliationsRoute
  '/finance/references': typeof FinanceReferencesRoute
  '/assets/': typeof AssetsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/finance/': typeof FinanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/references': typeof AssetsReferencesRoute
  '/auth/access-key': typeof AuthAccessKeyRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/references': typeof EmployeesReferencesRoute
  '/finance/journal-entries': typeof FinanceJournalEntriesRoute
  '/finance/reconciliations': typeof FinanceReconciliationsRoute
  '/finance/references': typeof FinanceReferencesRoute
  '/assets': typeof AssetsIndexRoute
  '/employees': typeof EmployeesIndexRoute
  '/finance': typeof FinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/assets/references': typeof AssetsReferencesRoute
  '/auth/access-key': typeof AuthAccessKeyRoute
  '/employees/$employeeId': typeof EmployeesEmployeeIdRoute
  '/employees/references': typeof EmployeesReferencesRoute
  '/finance/journal-entries': typeof FinanceJournalEntriesRoute
  '/finance/reconciliations': typeof FinanceReconciliationsRoute
  '/finance/references': typeof FinanceReferencesRoute
  '/assets/': typeof AssetsIndexRoute
  '/employees/': typeof EmployeesIndexRoute
  '/finance/': typeof FinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets/$assetId'
    | '/assets/references'
    | '/auth/access-key'
    | '/employees/$employeeId'
    | '/employees/references'
    | '/finance/journal-entries'
    | '/finance/reconciliations'
    | '/finance/references'
    | '/assets/'
    | '/employees/'
    | '/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets/$assetId'
    | '/assets/references'
    | '/auth/access-key'
    | '/employees/$employeeId'
    | '/employees/references'
    | '/finance/journal-entries'
    | '/finance/reconciliations'
    | '/finance/references'
    | '/assets'
    | '/employees'
    | '/finance'
  id:
    | '__root__'
    | '/'
    | '/assets/$assetId'
    | '/assets/references'
    | '/auth/access-key'
    | '/employees/$employeeId'
    | '/employees/references'
    | '/finance/journal-entries'
    | '/finance/reconciliations'
    | '/finance/references'
    | '/assets/'
    | '/employees/'
    | '/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  AssetsReferencesRoute: typeof AssetsReferencesRoute
  AuthAccessKeyRoute: typeof AuthAccessKeyRoute
  EmployeesEmployeeIdRoute: typeof EmployeesEmployeeIdRoute
  EmployeesReferencesRoute: typeof EmployeesReferencesRoute
  FinanceJournalEntriesRoute: typeof FinanceJournalEntriesRoute
  FinanceReconciliationsRoute: typeof FinanceReconciliationsRoute
  FinanceReferencesRoute: typeof FinanceReferencesRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  EmployeesIndexRoute: typeof EmployeesIndexRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/': {
      id: '/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/': {
      id: '/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof EmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/references': {
      id: '/finance/references'
      path: '/finance/references'
      fullPath: '/finance/references'
      preLoaderRoute: typeof FinanceReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/reconciliations': {
      id: '/finance/reconciliations'
      path: '/finance/reconciliations'
      fullPath: '/finance/reconciliations'
      preLoaderRoute: typeof FinanceReconciliationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/journal-entries': {
      id: '/finance/journal-entries'
      path: '/finance/journal-entries'
      fullPath: '/finance/journal-entries'
      preLoaderRoute: typeof FinanceJournalEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/references': {
      id: '/employees/references'
      path: '/employees/references'
      fullPath: '/employees/references'
      preLoaderRoute: typeof EmployeesReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees/$employeeId': {
      id: '/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof EmployeesEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/access-key': {
      id: '/auth/access-key'
      path: '/auth/access-key'
      fullPath: '/auth/access-key'
      preLoaderRoute: typeof AuthAccessKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/references': {
      id: '/assets/references'
      path: '/assets/references'
      fullPath: '/assets/references'
      preLoaderRoute: typeof AssetsReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  AssetsReferencesRoute: AssetsReferencesRoute,
  AuthAccessKeyRoute: AuthAccessKeyRoute,
  EmployeesEmployeeIdRoute: EmployeesEmployeeIdRoute,
  EmployeesReferencesRoute: EmployeesReferencesRoute,
  FinanceJournalEntriesRoute: FinanceJournalEntriesRoute,
  FinanceReconciliationsRoute: FinanceReconciliationsRoute,
  FinanceReferencesRoute: FinanceReferencesRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  EmployeesIndexRoute: EmployeesIndexRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
